apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
resources:
  - ../../base
  - ingress.yaml
secretGenerator:
  - name: healthcheck-env
    type: Opaque
    envs:
      - .env
generatorOptions:
  disableNameSuffixHash: true
labels:
  - includeSelectors: true
    pairs:
      variant: prod
patches:
  - path: deployment_patch.yaml
  - path: service_patch.yaml
  - path: statefulset_patch.yaml
images:
  - name: ghcr.io/dbca-wa/healthcheck
    newTag: 1.3.10
