apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: healthcheck-data
spec:
  storageClassName: azurefile-csi-retain
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
